[project]
name = "trigger-detent"
version = "0.1.2"
requires-python = "==3.12.9"
dependencies = [
    "pydirectinput-rgx>=2.1.3",
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.17.0",
]
